version: "3.8"
services:
  depccg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: depccg_parser_cpu
    # OR use the older runtime syntax:
    # runtime: nvidia
    tty: true
    stdin_open: true
    volumes:
      - ./:/workspace
      - ./src:/src
      - ./output:/workspace/output
    working_dir: /workspace